import httpx
from github import Github


def deploy(access_token: str, html_content: str, repo_name: str = "resume") -> str:
    """
    将生成好的简历 HTML 部署到用户的 GitHub Pages

    步骤：
    1. 用 access_token 获取用户信息
    2. 创建或获取已有的仓库
    3. 推送 index.html 文件
    4. 开启 GitHub Pages
    5. 返回最终的访问 URL

    access_token: GitHub OAuth 授权后的令牌
    html_content: 已渲染好的简历 HTML 字符串
    repo_name: 目标仓库名，默认为 resume
    """
    g = Github(access_token)
    user = g.get_user()
    username = user.login

    # 创建仓库（如果已存在则直接获取）
    try:
        repo = user.get_repo(repo_name)
    except Exception:
        repo = user.create_repo(
            repo_name,
            description="My resume — generated by cv-to-github-pages",
            auto_init=True,
        )

    # 推送 index.html（已存在则更新，不存在则创建）
    try:
        existing_file = repo.get_contents("index.html")
        repo.update_file(
            path="index.html",
            message="Update resume via cv-to-github-pages",
            content=html_content,
            sha=existing_file.sha,
        )
    except Exception:
        repo.create_file(
            path="index.html",
            message="Deploy resume via cv-to-github-pages",
            content=html_content,
        )

    # 调用 GitHub API 开启 Pages（PyGithub 暂不支持此接口，用 httpx 直接调用）
    httpx.post(
        f"https://api.github.com/repos/{username}/{repo_name}/pages",
        headers={
            "Authorization": f"Bearer {access_token}",
            "Accept": "application/vnd.github+json"
        },
        json={"source": {"branch": "main", "path": "/"}},
    )

    # 返回 GitHub Pages 地址
    return f"https://{username}.github.io/{repo_name}"